@MindWaveAPI_HostAddress = http://localhost:5119
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNmU4NGI0MC00ZDkyLTQzNjktYjFhMi02MzRkZmQ5ODkzZTkiLCJlbWFpbCI6InRlc3QxMjJKV1RAZXhhbXBsZS5jb20iLCJqdGkiOiI1NTY4MWRjMC0wYzEyLTRhZjMtOGUwYi00OTIxOWJkZjZlMDEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJQYXRpZW50IiwibmJmIjoxNzY1NTcyNzk1LCJleHAiOjE3NjU1NzYzOTUsImlzcyI6Ik1pbmRXYXZlQVBJIiwiYXVkIjoiTWluZFdhdmVBUElDbGllbnRzIn0.GiU9hisPbzJmXZPEMqbsB6YgRYry0Ijpwtw290VWuYw
@patient_user_id = 06e84b40-4d92-4369-b1a2-634dfd9893e9
@survey_instance_id = 69851576-ec84-44c1-9b91-12cef44e9bee
@category = hypomania # "depression" | "hypomania" | "mania"

### Register user
POST {{MindWaveAPI_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "test122JWT@example.com",
  "password": "P@ssw0rd!",
  "role": "Patient"
}

### Login user (copy token and userId from response above)
POST {{MindWaveAPI_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "test122JWT@example.com",
  "password": "P@ssw0rd!"
}

### Submit initial daily survey answers (one per day enforced)
POST {{MindWaveAPI_HostAddress}}/api/surveys/daily/initial
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "date": "2025-12-10",
  "answer1": 5,
  "answer2": 4,
  "answer3": 3,
  "answer4": 6
}

### Get category (replace with actual surveyInstanceId from initial response)
GET {{MindWaveAPI_HostAddress}}/api/surveys/daily/{{survey_instance_id}}/category
Accept: application/json
Authorization: Bearer {{access_token}}

### Submit follow-up for Depression
POST {{MindWaveAPI_HostAddress}}/api/surveys/daily/followup
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "surveyInstanceId": "{{survey_instance_id}}",
  "category": "depression",
  "answers": {
    "101": 4,
    "102": 3,
    "103": 6,
    "104": 2,
    "105": 5,
    "106": 4,
    "107": 5
  }
}

### Submit follow-up for Hypomania
POST {{MindWaveAPI_HostAddress}}/api/surveys/daily/followup
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "surveyInstanceId": "{{survey_instance_id}}",
  "category": "hypomania",
  "answers": {
    "201": 6,
    "202": 7,
    "203": 3,
    "204": 6,
    "205": 10
  }
}

### Submit follow-up for Mania
POST {{MindWaveAPI_HostAddress}}/api/surveys/daily/followup
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "surveyInstanceId": "{{survey_instance_id}}",
  "category": "mania",
  "answers": {
    "301": 8,
    "302": 8,
    "303": 2,
    "304": 7,
    "305": 9,
    "306": 8
  }
}